import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals/variables.scss';
import 'animate.css';
import AuthProvider from '../lib/authProvider/authProvider';
import { Inter } from 'next/font/google';
import TokenExpiration from '../lib/tokenExpiration/tokenExpiration';

export const metadata = {
  title: 'PixelBoard',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  families: ['Inter'],
  display: 'swap',
  weight: '400',
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-soft-gray `}>
        <AuthProvider>
          <TokenExpiration>{children}</TokenExpiration>
        </AuthProvider>
      </body>
    </html>
  );
}
